# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacuna',
            new_name='Marca',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='edad_aproximada',
            new_name='cantidad',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='fecha_rescate',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='vacuna',
        ),
        migrations.AddField(
            model_name='mascota',
            name='color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascota',
            name='marca',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='mascota.Marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascota',
            name='precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
